name: Test Python version
run-name: ${{ github.actor }} is testing out python version 🚀
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        # strategy:
        #     matrix:
        #         python-version: [3.6, 3.7, 3.8, 3.9, 3.10]
        steps:
        - name: checkout git repo
          uses: actions/checkout@v2
        - name: Set up Python 
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
        - name: Install dependencies
          run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
        - name: Checking Python version
          run: python -V
        # - name: Run tests
        #   run: |
        #         pytest
